//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.14 at 09:33:21 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://walterwhites.io/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.walterwhites.webservice;
