//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.15 at 03:21:03 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "java.jaxb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jaxb.java;
